<?php

$hasSLang = class_exists('Seiger\\sLang\\sLang');
$domains = app(\Seiger\sMailer\Services\DomainContext::class);
$hasSMultisite = $domains->hasMultisite();

return [
    'key' => 'smailer.subscribers',
    'provider' => \Seiger\sMailer\Tables\SubscribersTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,setSort,switchView',
    'per_page' => 30,
    'per_page_options' => [15, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'subscribed_at',
    'default_direction' => 'desc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'placeholder' => 'sMailer::global.search_subscribers',
    ],
    'actions' => [
        [
            'key' => 'import',
            'type' => 'link',
            'icon' => 'file-import',
            'label' => 'sMailer::global.subscribers_import_csv',
            'tone' => 'success',
            'variant' => 'filled',
            'href' => '#',
            'attributes' => ['x-on:click.prevent' => "\$dispatch('smailer-subscribers-import')"],
        ],
        [
            'key' => 'export',
            'type' => 'link',
            'icon' => 'file-export',
            'label' => 'sMailer::global.subscribers_export_csv',
            'tone' => 'info',
            'href' => '#',
            'attributes' => ['x-on:click.prevent' => "\$dispatch('smailer-subscribers-export')"],
        ],
    ],
    'filters' => [[
        'state' => 'status',
        'type' => 'multi-select',
        'icon' => 'circle-check',
        'label' => 'sMailer::global.subscriber_status',
        'searchable' => false,
        'default' => [],
    ]],
    'columns' => [
        [
            'key' => 'email',
            'type' => 'text',
            'label' => 'sMailer::global.subscriber_email',
            'cell_class' => 'evo-ui-table__title-column evo-ui-table__title-text',
            'sortable' => true,
            'sort_field' => 'email',
        ],
        ...($hasSMultisite ? [[
            'key' => 'domain_display',
            'type' => 'text',
            'label' => 'sMailer::global.domain',
            'sortable' => true,
            'sort_field' => 'domain',
        ]] : []),
        ...($hasSLang ? [[
            'key' => 'lang',
            'type' => 'text',
            'label' => 'sMailer::global.language',
            'sortable' => true,
            'sort_field' => 'lang',
        ]] : []),
        [
            'key' => 'name',
            'type' => 'text',
            'label' => 'sMailer::global.subscriber_name',
        ],
        [
            'key' => 'status_display',
            'type' => 'chips',
            'label' => 'sMailer::global.subscriber_status',
            'sortable' => true,
            'sort_field' => 'status',
        ],
        [
            'key' => 'subscribed_at',
            'type' => 'text',
            'label' => 'sMailer::global.subscriber_subscribed_at',
            'sortable' => true,
            'sort_field' => 'subscribed_at',
            'meta_icon' => 'calendar-time',
        ],
    ],
    'list' => [
        'media' => true,
        'icon' => 'user',
        'title' => 'email',
        'subtitle' => 'name',
        'meta' => ['status_display', 'subscribed_at'],
    ],
    'row_actions' => [
        [
            'key' => 'subscription',
            'type' => 'wire',
            'method' => 'runRowAction',
            'action_argument' => true,
            'provider' => 'toggleSubscription',
            'argument' => 'id',
            'icon_field' => 'is_unsubscribed',
            'icon_true' => 'mail-check',
            'icon_false' => 'mail-off',
            'label_field' => 'is_unsubscribed',
            'label_true' => 'sMailer::global.subscriber_subscribe',
            'label_false' => 'sMailer::global.subscriber_unsubscribe',
            'tone_field' => 'is_unsubscribed',
            'tone_true' => 'success',
            'tone_false' => 'warning',
            'disabled_field' => 'subscription_disabled',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'sMailer::global.subscriber_delete',
            'tone' => 'danger',
        ],
    ],
];
