<?php

$hasSLang = class_exists('Seiger\\sLang\\sLang');
$domains = app(\Seiger\sMailer\Services\DomainContext::class);
$hasSMultisite = $domains->hasMultisite();
$domainOptions = $domains->options();

return [
    'key' => 'smailer.mailings',
    'provider' => \Seiger\sMailer\Tables\MailingsTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,setSort,switchView,openEditModal,saveModal,closeModal',
    'per_page' => 30,
    'per_page_options' => [15, 30, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'name',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'placeholder' => 'sMailer::global.search_mailings',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'link',
            'icon' => 'plus',
            'label' => 'sMailer::global.create_mailing',
            'tone' => 'success',
            'icon_only' => true,
            'href_provider' => 'editorUrl',
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'sMailer::global.edit_mailing',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'template',
            'type' => 'link',
            'icon' => 'template',
            'label' => 'sMailer::global.edit_template',
            'tone' => 'info',
            'icon_only' => true,
            'selection' => 'single',
            'href_provider' => 'editorUrl',
        ],
        [
            'key' => 'duplicate',
            'type' => 'placeholder',
            'icon' => 'copy',
            'label' => 'sMailer::global.duplicate_mailing',
            'tone' => 'info',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'placeholder',
            'icon' => 'trash',
            'label' => 'sMailer::global.delete_mailing',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => false,
        'icon' => 'settings',
        'size' => 'md',
        'title_edit' => 'sMailer::global.campaign_details',
        'submit_label' => 'sMailer::global.campaign_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            [
                'name' => 'name',
                'type' => 'text',
                'label' => 'sMailer::global.campaign_name',
                'rules' => ['required', 'string', 'max:255'],
                'span' => 'full',
            ],
            ...($hasSMultisite ? [[
                'name' => 'domain',
                'type' => 'select',
                'label' => 'sMailer::global.domain',
                'rules' => ['required', 'string', 'max:100'],
                'options' => $domainOptions,
            ]] : []),
            ...($hasSLang ? [[
                'name' => 'lang',
                'type' => 'text',
                'label' => 'sMailer::global.language',
                'rules' => ['required', 'string', 'max:20'],
            ]] : []),
            [
                'name' => 'status',
                'type' => 'select',
                'label' => 'sMailer::global.mailing_status',
                'rules' => ['required', 'in:draft,ready,active,paused'],
                'options' => [
                    ['value' => 'draft', 'label' => 'sMailer::global.mailing_status_draft'],
                    ['value' => 'ready', 'label' => 'sMailer::global.mailing_status_ready'],
                    ['value' => 'active', 'label' => 'sMailer::global.mailing_status_active'],
                    ['value' => 'paused', 'label' => 'sMailer::global.mailing_status_paused'],
                ],
            ],
            [
                'name' => 'delivery_mode',
                'type' => 'select',
                'label' => 'sMailer::global.mailing_delivery_mode',
                'rules' => ['required', 'in:manual,once,recurring'],
                'options' => [
                    ['value' => 'manual', 'label' => 'sMailer::global.delivery_manual'],
                    ['value' => 'once', 'label' => 'sMailer::global.delivery_once'],
                    ['value' => 'recurring', 'label' => 'sMailer::global.delivery_recurring'],
                ],
            ],
            [
                'name' => 'scheduled_at',
                'type' => 'datetime-local',
                'label' => 'sMailer::global.mailing_scheduled_at',
                'min' => now()->format('Y-m-d\\TH:i'),
                'rules' => ['nullable', 'date', 'required_if:delivery_mode,once'],
                'span' => 'full',
                'visible_if' => [
                    'field' => 'delivery_mode',
                    'value' => 'once',
                ],
            ],
            [
                'name' => 'recurrence_frequency',
                'type' => 'select',
                'label' => 'sMailer::global.mailing_recurrence_frequency',
                'rules' => ['required_if:delivery_mode,recurring', 'in:daily,weekly,monthly'],
                'options' => [
                    ['value' => 'daily', 'label' => 'sMailer::global.recurrence_daily'],
                    ['value' => 'weekly', 'label' => 'sMailer::global.recurrence_weekly'],
                    ['value' => 'monthly', 'label' => 'sMailer::global.recurrence_monthly'],
                ],
                'visible_if' => [
                    'field' => 'delivery_mode',
                    'value' => 'recurring',
                ],
            ],
            [
                'name' => 'recurrence_time',
                'type' => 'time',
                'label' => 'sMailer::global.mailing_recurrence_time',
                'rules' => ['required_if:delivery_mode,recurring', 'date_format:H:i'],
                'visible_if' => [
                    'field' => 'delivery_mode',
                    'value' => 'recurring',
                ],
            ],
            [
                'name' => 'recurrence_weekday',
                'type' => 'select',
                'label' => 'sMailer::global.mailing_recurrence_weekday',
                'rules' => ['required_if:recurrence_frequency,weekly', 'in:sunday,monday,tuesday,wednesday,thursday,friday,saturday'],
                'options' => [
                    ['value' => 'monday', 'label' => 'sMailer::global.weekday_monday'],
                    ['value' => 'tuesday', 'label' => 'sMailer::global.weekday_tuesday'],
                    ['value' => 'wednesday', 'label' => 'sMailer::global.weekday_wednesday'],
                    ['value' => 'thursday', 'label' => 'sMailer::global.weekday_thursday'],
                    ['value' => 'friday', 'label' => 'sMailer::global.weekday_friday'],
                    ['value' => 'saturday', 'label' => 'sMailer::global.weekday_saturday'],
                    ['value' => 'sunday', 'label' => 'sMailer::global.weekday_sunday'],
                ],
                'visible_if_all' => [
                    ['field' => 'delivery_mode', 'value' => 'recurring'],
                    ['field' => 'recurrence_frequency', 'value' => 'weekly'],
                ],
            ],
            [
                'name' => 'recurrence_day_of_month',
                'type' => 'number',
                'label' => 'sMailer::global.mailing_recurrence_day_of_month',
                'min' => 1,
                'max' => 31,
                'rules' => ['required_if:recurrence_frequency,monthly', 'integer', 'between:1,31'],
                'visible_if_all' => [
                    ['field' => 'delivery_mode', 'value' => 'recurring'],
                    ['field' => 'recurrence_frequency', 'value' => 'monthly'],
                ],
            ],
        ],
    ],
    'filters' => [
        [
            'state' => 'status',
            'type' => 'multi-select',
            'icon' => 'circle-check',
            'label' => 'sMailer::global.mailing_status',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'delivery_mode',
            'type' => 'multi-select',
            'icon' => 'calendar-time',
            'label' => 'sMailer::global.mailing_delivery_mode',
            'searchable' => false,
            'default' => [],
        ],
    ],
    'columns' => [
        [
            'key' => 'name',
            'type' => 'text',
            'label' => 'sMailer::global.mailing_name',
            'cell_class' => 'evo-ui-table__title-column evo-ui-table__title-text',
            'sortable' => true,
            'sort_field' => 'name',
        ],
        ...($hasSMultisite ? [[
            'key' => 'domain_display',
            'type' => 'text',
            'label' => 'sMailer::global.domain',
            'sortable' => true,
            'sort_field' => 'domain',
        ]] : []),
        ...($hasSLang ? [[
            'key' => 'lang',
            'type' => 'text',
            'label' => 'sMailer::global.language',
            'sortable' => true,
            'sort_field' => 'lang',
        ]] : []),
        [
            'key' => 'status_display',
            'type' => 'chips',
            'label' => 'sMailer::global.mailing_status',
            'sortable' => true,
            'sort_field' => 'status',
        ],
        [
            'key' => 'delivery_display',
            'type' => 'chips',
            'label' => 'sMailer::global.mailing_delivery_mode',
            'sortable' => true,
            'sort_field' => 'delivery_mode',
        ],
        [
            'key' => 'next_delivery',
            'type' => 'text',
            'label' => 'sMailer::global.mailing_next_delivery',
            'sortable' => true,
            'sort_field' => 'next_delivery',
            'meta_icon' => 'clock',
        ],
    ],
    'list' => [
        'media' => true,
        'icon' => 'mail',
        'title' => 'name',
        'subtitle' => 'description',
        'meta' => ['status_display', 'delivery_display', 'next_delivery'],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'sMailer::global.edit_mailing',
            'tone' => 'primary',
        ],
        [
            'key' => 'template',
            'type' => 'link',
            'icon' => 'template',
            'label' => 'sMailer::global.edit_template',
            'tone' => 'info',
            'href' => 'editor_url',
        ],
        [
            'key' => 'preview',
            'type' => 'link',
            'icon' => 'eye',
            'label' => 'sMailer::global.builder_preview',
            'tone' => 'info',
            'href' => '#',
            'attributes' => [
                'x-on:click.prevent' => 'preview_action',
            ],
        ],
        [
            'key' => 'send_once',
            'type' => 'link',
            'icon' => 'send',
            'label' => 'sMailer::global.mailing_send_once',
            'tone' => 'success',
            'href' => '#',
            'attributes' => [
                'x-on:click.prevent' => 'queue_action',
            ],
        ],
        [
            'key' => 'duplicate',
            'type' => 'placeholder',
            'icon' => 'copy',
            'label' => 'sMailer::global.duplicate_mailing',
            'tone' => 'info',
        ],
        [
            'key' => 'delete',
            'type' => 'placeholder',
            'icon' => 'trash',
            'label' => 'sMailer::global.delete_mailing',
            'tone' => 'danger',
        ],
    ],
];
